/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CreateMediaParams
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-21T10:43:19.319+01:00")
public class CreateMediaParams {
  @SerializedName("name")
  private String name = null;

  @SerializedName("origin")
  private String origin = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("tts_voice")
  private String ttsVoice = null;

  @SerializedName("tts_text")
  private String ttsText = null;

  @SerializedName("is_temparary")
  private String isTemparary = null;

  @SerializedName("expiration_date")
  private Integer expirationDate = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("randomized")
  private String randomized = null;

  public CreateMediaParams name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of media
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of media")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateMediaParams origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * 'tts', 'file'
   * @return origin
  **/
  @ApiModelProperty(example = "null", value = "'tts', 'file'")
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public CreateMediaParams type(String type) {
    this.type = type;
    return this;
  }

   /**
   * 'hold_music', 'greeting'
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "'hold_music', 'greeting'")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CreateMediaParams ttsVoice(String ttsVoice) {
    this.ttsVoice = ttsVoice;
    return this;
  }

   /**
   * 'allison', 'amy', 'belle', 'callie', 'callieq', 'dallas', 'damien', 'david', 'designerdave', 'diane', 'diesel', 'dog', 'duchess', 'duncan', 'emily', 'evilgenius', 'frank', 'french-fry', 'gregory', 'isabelle', 'jean-pierre', 'jerkface', 'katrin', 'kayla', 'kidaroo', 'lawrence', 'layo', 'linda', 'marta', 'matthias', 'miguel', 'millie', 'princess', 'ransomnote', 'robin', 'shouty', 'shygirl', 'tamika', 'tophat', 'vittoria', 'vixen', 'vlad', 'walter', 'whispery', 'william', 'wiseguy', 'zach'
   * @return ttsVoice
  **/
  @ApiModelProperty(example = "null", value = "'allison', 'amy', 'belle', 'callie', 'callieq', 'dallas', 'damien', 'david', 'designerdave', 'diane', 'diesel', 'dog', 'duchess', 'duncan', 'emily', 'evilgenius', 'frank', 'french-fry', 'gregory', 'isabelle', 'jean-pierre', 'jerkface', 'katrin', 'kayla', 'kidaroo', 'lawrence', 'layo', 'linda', 'marta', 'matthias', 'miguel', 'millie', 'princess', 'ransomnote', 'robin', 'shouty', 'shygirl', 'tamika', 'tophat', 'vittoria', 'vixen', 'vlad', 'walter', 'whispery', 'william', 'wiseguy', 'zach'")
  public String getTtsVoice() {
    return ttsVoice;
  }

  public void setTtsVoice(String ttsVoice) {
    this.ttsVoice = ttsVoice;
  }

  public CreateMediaParams ttsText(String ttsText) {
    this.ttsText = ttsText;
    return this;
  }

   /**
   * Text used for text-to-speech conversion, maximum 800 characters
   * @return ttsText
  **/
  @ApiModelProperty(example = "null", value = "Text used for text-to-speech conversion, maximum 800 characters")
  public String getTtsText() {
    return ttsText;
  }

  public void setTtsText(String ttsText) {
    this.ttsText = ttsText;
  }

  public CreateMediaParams isTemparary(String isTemparary) {
    this.isTemparary = isTemparary;
    return this;
  }

   /**
   * 'Y', 'N'. Media file is temporary, will be deleted after a specified period.
   * @return isTemparary
  **/
  @ApiModelProperty(example = "null", value = "'Y', 'N'. Media file is temporary, will be deleted after a specified period.")
  public String getIsTemparary() {
    return isTemparary;
  }

  public void setIsTemparary(String isTemparary) {
    this.isTemparary = isTemparary;
  }

  public CreateMediaParams expirationDate(Integer expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * If is_temporary is 'Y', media will be deleted after the specified time in seconds
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", value = "If is_temporary is 'Y', media will be deleted after the specified time in seconds")
  public Integer getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(Integer expirationDate) {
    this.expirationDate = expirationDate;
  }

  public CreateMediaParams duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Length of media in seconds
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "Length of media in seconds")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public CreateMediaParams notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Notes about the media object
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "Notes about the media object")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public CreateMediaParams randomized(String randomized) {
    this.randomized = randomized;
    return this;
  }

   /**
   * 'Y', 'N'. Start playing the media file in random location, instead of from the beginning
   * @return randomized
  **/
  @ApiModelProperty(example = "null", value = "'Y', 'N'. Start playing the media file in random location, instead of from the beginning")
  public String getRandomized() {
    return randomized;
  }

  public void setRandomized(String randomized) {
    this.randomized = randomized;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMediaParams createMediaParams = (CreateMediaParams) o;
    return Objects.equals(this.name, createMediaParams.name) &&
        Objects.equals(this.origin, createMediaParams.origin) &&
        Objects.equals(this.type, createMediaParams.type) &&
        Objects.equals(this.ttsVoice, createMediaParams.ttsVoice) &&
        Objects.equals(this.ttsText, createMediaParams.ttsText) &&
        Objects.equals(this.isTemparary, createMediaParams.isTemparary) &&
        Objects.equals(this.expirationDate, createMediaParams.expirationDate) &&
        Objects.equals(this.duration, createMediaParams.duration) &&
        Objects.equals(this.notes, createMediaParams.notes) &&
        Objects.equals(this.randomized, createMediaParams.randomized);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, origin, type, ttsVoice, ttsText, isTemparary, expirationDate, duration, notes, randomized);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMediaParams {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ttsVoice: ").append(toIndentedString(ttsVoice)).append("\n");
    sb.append("    ttsText: ").append(toIndentedString(ttsText)).append("\n");
    sb.append("    isTemparary: ").append(toIndentedString(isTemparary)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    randomized: ").append(toIndentedString(randomized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

