/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * FilterListPhoneNumbersRegions
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-03T13:11:20.199+02:00")
public class FilterListPhoneNumbersRegions   {
  @SerializedName("country_code")
  private List<String> countryCode = new ArrayList<String>();

  @SerializedName("npa")
  private List<Integer> npa = new ArrayList<Integer>();

  @SerializedName("nxx")
  private List<String> nxx = new ArrayList<String>();

  @SerializedName("is_toll_free")
  private List<String> isTollFree = new ArrayList<String>();

  @SerializedName("city")
  private List<String> city = new ArrayList<String>();

  @SerializedName("province_postal_code")
  private List<String> provincePostalCode = new ArrayList<String>();

  @SerializedName("country_postal_code")
  private List<String> countryPostalCode = new ArrayList<String>();

  public FilterListPhoneNumbersRegions countryCode(List<String> countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  public FilterListPhoneNumbersRegions addCountryCodeItem(String countryCodeItem) {
    this.countryCode.add(countryCodeItem);
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(List<String> countryCode) {
    this.countryCode = countryCode;
  }

  public FilterListPhoneNumbersRegions npa(List<Integer> npa) {
    this.npa = npa;
    return this;
  }

  public FilterListPhoneNumbersRegions addNpaItem(Integer npaItem) {
    this.npa.add(npaItem);
    return this;
  }

   /**
   * Get npa
   * @return npa
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Integer> getNpa() {
    return npa;
  }

  public void setNpa(List<Integer> npa) {
    this.npa = npa;
  }

  public FilterListPhoneNumbersRegions nxx(List<String> nxx) {
    this.nxx = nxx;
    return this;
  }

  public FilterListPhoneNumbersRegions addNxxItem(String nxxItem) {
    this.nxx.add(nxxItem);
    return this;
  }

   /**
   * Get nxx
   * @return nxx
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNxx() {
    return nxx;
  }

  public void setNxx(List<String> nxx) {
    this.nxx = nxx;
  }

  public FilterListPhoneNumbersRegions isTollFree(List<String> isTollFree) {
    this.isTollFree = isTollFree;
    return this;
  }

  public FilterListPhoneNumbersRegions addIsTollFreeItem(String isTollFreeItem) {
    this.isTollFree.add(isTollFreeItem);
    return this;
  }

   /**
   * Get isTollFree
   * @return isTollFree
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getIsTollFree() {
    return isTollFree;
  }

  public void setIsTollFree(List<String> isTollFree) {
    this.isTollFree = isTollFree;
  }

  public FilterListPhoneNumbersRegions city(List<String> city) {
    this.city = city;
    return this;
  }

  public FilterListPhoneNumbersRegions addCityItem(String cityItem) {
    this.city.add(cityItem);
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCity() {
    return city;
  }

  public void setCity(List<String> city) {
    this.city = city;
  }

  public FilterListPhoneNumbersRegions provincePostalCode(List<String> provincePostalCode) {
    this.provincePostalCode = provincePostalCode;
    return this;
  }

  public FilterListPhoneNumbersRegions addProvincePostalCodeItem(String provincePostalCodeItem) {
    this.provincePostalCode.add(provincePostalCodeItem);
    return this;
  }

   /**
   * Get provincePostalCode
   * @return provincePostalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getProvincePostalCode() {
    return provincePostalCode;
  }

  public void setProvincePostalCode(List<String> provincePostalCode) {
    this.provincePostalCode = provincePostalCode;
  }

  public FilterListPhoneNumbersRegions countryPostalCode(List<String> countryPostalCode) {
    this.countryPostalCode = countryPostalCode;
    return this;
  }

  public FilterListPhoneNumbersRegions addCountryPostalCodeItem(String countryPostalCodeItem) {
    this.countryPostalCode.add(countryPostalCodeItem);
    return this;
  }

   /**
   * Get countryPostalCode
   * @return countryPostalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCountryPostalCode() {
    return countryPostalCode;
  }

  public void setCountryPostalCode(List<String> countryPostalCode) {
    this.countryPostalCode = countryPostalCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterListPhoneNumbersRegions filterListPhoneNumbersRegions = (FilterListPhoneNumbersRegions) o;
    return Objects.equals(this.countryCode, filterListPhoneNumbersRegions.countryCode) &&
        Objects.equals(this.npa, filterListPhoneNumbersRegions.npa) &&
        Objects.equals(this.nxx, filterListPhoneNumbersRegions.nxx) &&
        Objects.equals(this.isTollFree, filterListPhoneNumbersRegions.isTollFree) &&
        Objects.equals(this.city, filterListPhoneNumbersRegions.city) &&
        Objects.equals(this.provincePostalCode, filterListPhoneNumbersRegions.provincePostalCode) &&
        Objects.equals(this.countryPostalCode, filterListPhoneNumbersRegions.countryPostalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, npa, nxx, isTollFree, city, provincePostalCode, countryPostalCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterListPhoneNumbersRegions {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    npa: ").append(toIndentedString(npa)).append("\n");
    sb.append("    nxx: ").append(toIndentedString(nxx)).append("\n");
    sb.append("    isTollFree: ").append(toIndentedString(isTollFree)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    provincePostalCode: ").append(toIndentedString(provincePostalCode)).append("\n");
    sb.append("    countryPostalCode: ").append(toIndentedString(countryPostalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

