/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * FilterCallLogs
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-03T13:11:20.199+02:00")
public class FilterCallLogs   {
  @SerializedName("id")
  private List<String> id = new ArrayList<String>();

  @SerializedName("start_time")
  private List<String> startTime = new ArrayList<String>();

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("direction")
  private String direction = null;

  @SerializedName("called_number")
  private String calledNumber = null;

  @SerializedName("type")
  private String type = null;

  public FilterCallLogs id(List<String> id) {
    this.id = id;
    return this;
  }

  public FilterCallLogs addIdItem(String idItem) {
    this.id.add(idItem);
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getId() {
    return id;
  }

  public void setId(List<String> id) {
    this.id = id;
  }

  public FilterCallLogs startTime(List<String> startTime) {
    this.startTime = startTime;
    return this;
  }

  public FilterCallLogs addStartTimeItem(String startTimeItem) {
    this.startTime.add(startTimeItem);
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getStartTime() {
    return startTime;
  }

  public void setStartTime(List<String> startTime) {
    this.startTime = startTime;
  }

  public FilterCallLogs createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public FilterCallLogs direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public FilterCallLogs calledNumber(String calledNumber) {
    this.calledNumber = calledNumber;
    return this;
  }

   /**
   * Get calledNumber
   * @return calledNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCalledNumber() {
    return calledNumber;
  }

  public void setCalledNumber(String calledNumber) {
    this.calledNumber = calledNumber;
  }

  public FilterCallLogs type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterCallLogs filterCallLogs = (FilterCallLogs) o;
    return Objects.equals(this.id, filterCallLogs.id) &&
        Objects.equals(this.startTime, filterCallLogs.startTime) &&
        Objects.equals(this.createdAt, filterCallLogs.createdAt) &&
        Objects.equals(this.direction, filterCallLogs.direction) &&
        Objects.equals(this.calledNumber, filterCallLogs.calledNumber) &&
        Objects.equals(this.type, filterCallLogs.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startTime, createdAt, direction, calledNumber, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterCallLogs {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    calledNumber: ").append(toIndentedString(calledNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

