/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.Configuration;
import io.swagger.client.auth.ApiKeyAuth;
import io.swagger.client.model.AccountFull;
import io.swagger.client.model.ListAccountsFull;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Retrieve details of an individual account
     *
     * This service shows the details of an individual account. See Accounts for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountTest() throws ApiException {
    	 ApiClient defaultClient = Configuration.getDefaultApiClient();
         
         // Configure API key authorization: apiKey
         ApiKeyAuth apiKey = (ApiKeyAuth) defaultClient.getAuthentication("apiKey");
         apiKey.setApiKeyPrefix("Bearer");
         apiKey.setApiKey("FJxqBQcorvEVFPpDVPuZAeYdT5kMrWo1cFxwGE7u");
         // Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
         //apiKey.setApiKeyPrefix("Token");
        
    	//Integer accountId = 33;
        
    	
    	//AccountFull response = api.getAccount(accountId);

        // TODO: test validations
    }
    
    /**
     * Get a list of accounts visible to the authenticated user or client
     *
     * This service lists the accounts accessible to the authenticated client. In most cases, there will only be one such account. See Accounts for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountsTest() throws ApiException {
        List<String> filtersId = null;
        String sortId = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        
        // Configure API key authorization: apiKey
        ApiKeyAuth apiKey = (ApiKeyAuth) defaultClient.getAuthentication("apiKey");
        apiKey.setApiKeyPrefix("Bearer");
        apiKey.setApiKey("FJxqBQcorvEVFPpDVPuZAeYdT5kMrWo1cFxwGE7u");
        // Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
        //apiKey.setApiKeyPrefix("Token");
       
         ListAccountsFull response = api.listAccounts(filtersId, sortId, limit, offset, fields);
         System.out.println(response);
        // TODO: test validations
    }
    
}
