/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import static org.junit.Assert.assertNotNull;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.model.CallFull;
import io.swagger.client.model.CreateCallParams;

/**
 * API tests for CallsApi
 */
@Ignore
public class CallsApiTest {

    private final CallsApi api = new CallsApi();

    
    /**
     * Make a phone call
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountCallsTest() throws ApiException {
        Integer accountId = null;
        CreateCallParams data = null;
        CallFull response = api.createAccountCall(accountId, data);

        assertNotNull(response);
    }
    
}
