/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.helper.TestConfig;
import io.swagger.client.model.ApplicationFull;
import io.swagger.client.model.CallLogFull;
import io.swagger.client.model.FilterCallLogs;
import io.swagger.client.model.FilterIdNameArray;
import io.swagger.client.model.ListCallLogsFull;
import io.swagger.client.model.SortCallLogs;
import io.swagger.client.model.SortIdName;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CalllogsApi
 */
public class CalllogsApiTest {

    private final CalllogsApi api = new CalllogsApi();

    @Before
    public void initTest() {
    	TestConfig.setAuthorization();
    }
    
    /**
     * Get a list of call details associated with your account
     *
     * Fetch a list of call logs associated with your account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountCallLogsTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersStartTime = null;
        String filtersCreatedAt = null;
        String filtersDirection = null;
        String filtersCalledNumber = null;
        String filtersType = null;
        List<String> filtersExtension = null;
        String sortId = null;
        String sortStartTime = null;
        String sortCreatedAt = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListCallLogsFull response = api.listAccountCallLogs(accountId, filtersId, filtersStartTime, filtersCreatedAt, filtersDirection, filtersCalledNumber, filtersType, filtersExtension, sortId, sortStartTime, sortCreatedAt, limit, offset, fields);

        assertNotNull(response);
        List<CallLogFull> items = response.getItems();
        assertNotNull(items);
        FilterCallLogs filters = response.getFilters();
        assertNotNull(filters);
        Integer limit2 = response.getLimit();
        assertNotNull(limit2);
        Integer offset2 = response.getOffset();
        assertNotNull(offset2);
        SortCallLogs sort = response.getSort();
        assertNotNull(sort);
    }
    
}
