/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import static io.swagger.client.helper.TestConfig.GREATER_THAN_FILTER;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Before;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.helper.TestConfig;
import io.swagger.client.model.ContactFull;
import io.swagger.client.model.CreateContactParams;
import io.swagger.client.model.FilterIdGroupIdUpdatedAtArray;
import io.swagger.client.model.ListContactsFull;
import io.swagger.client.model.SortIdUpdatedAt;
/**
 * API tests for ContactsApi
 */
public class ContactsApiTest {

    private final ContactsApi api = new ContactsApi();

    @Before
    public void initTest() {
    	TestConfig.setAuthorization();
    }
    
    /**
     * Add a new address book contact for an extension
     *
     * For more on the input fields, see Account Contacts.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountExtensionContactTest() throws ApiException {
        Integer accountId = null;
        Integer extensionId = null;
        CreateContactParams data = null;
        // ContactFull response = api.createAccountExtensionContact(accountId, extensionId, data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountExtensionContactTest() throws ApiException {
        Integer accountId = null;
        Integer extensionId = null;
        Integer contactId = null;
        // DeleteContact response = api.deleteAccountExtensionContact(accountId, extensionId, contactId);

        // TODO: test validations
    }
    
    /**
     * Retrieve the details of an address book contact
     *
     * For more info on the fields shown, see Account Contacts.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountExtensionContactTest() throws ApiException {
        Integer accountId = 1315091;
        Integer extensionId = 1764590;
        Integer contactId = null;
        ContactFull response = api.getAccountExtensionContact(accountId, extensionId, contactId);
        
        assertNotNull(response);

        // TODO: test validations
    }
    
    /**
     * Show a list of address book contacts
     *
     * See Account Contacts for more info on the fields in each item.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountExtensionContactsTest() throws ApiException {
    	
    	Integer accountId = 1315091;
        Integer extensionId = 1764590;
        List<String> filtersId = TestConfig.createDefaultFilter();
        List<String> filtersGroupId = TestConfig.createDefaultFilter();
        List<String> filtersUpdatedAt = TestConfig.createDefaultFilter();
        String sortId = "asc";
        String sortUpdatedAt = "asc";
        Integer limit = 4;
        Integer offset = 1;
        String fields = null;
        
        // When
        ListContactsFull response = api.listAccountExtensionContacts(accountId, extensionId, filtersId, filtersGroupId, filtersUpdatedAt, sortId, sortUpdatedAt, limit, offset, fields);

        // Then
        assertNotNull(response);
        List<ContactFull> items = response.getItems();
        assertNotNull(items);
        
        FilterIdGroupIdUpdatedAtArray filters = response.getFilters();
        assertNotNull(filters);
        assertEquals(GREATER_THAN_FILTER, filters.getId());
        
        assertEquals(GREATER_THAN_FILTER, filters.getGroupId());
        
        assertEquals(GREATER_THAN_FILTER, filters.getUpdatedAt());
        
        Integer limitActual = response.getLimit();
        assertNotNull(limitActual);
        assertEquals(limit, limitActual);
        
        Integer offsetActual = response.getOffset();
        assertNotNull(offsetActual);
        assertEquals(offset, offsetActual);
        
        SortIdUpdatedAt sort = response.getSort();
        assertNotNull(sort);
        assertEquals(sortId, sort.getId());
        
        assertEquals(sortUpdatedAt, sort.getUpdatedAt());
    }
    
    /**
     * 
     *
     * For more on the input fields, see Account Contacts.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountExtensionContactTest() throws ApiException {
        Integer accountId = null;
        Integer extensionId = null;
        CreateContactParams data = null;
        // ContactFull response = api.replaceAccountExtensionContact(accountId, extensionId, data);

        // TODO: test validations
    }
    
}
