/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExpressServiceCodeFull;
import io.swagger.client.model.ListExpressServiceCodesFull;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExpressservicecodesApi
 */
public class ExpressservicecodesApiTest {

    private final ExpressservicecodesApi api = new ExpressservicecodesApi();

    
    /**
     * Show details of an account Express Service Code
     *
     * This service shows the details of an Account Express Service Code.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountExpressSrvCodeTest() throws ApiException {
        Integer accountId = null;
        Integer codeId = null;
        // ExpressServiceCodeFull response = api.getAccountExpressSrvCode(accountId, codeId);

        // TODO: test validations
    }
    
    /**
     * Get the Express Service Code associated with your account in list format
     *
     * See Express Service Codes for more detail.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountExpressSrvCodesTest() throws ApiException {
        Integer accountId = null;
        List<String> filtersId = null;
        // ListExpressServiceCodesFull response = api.listAccountExpressSrvCodes(accountId, filtersId);

        // TODO: test validations
    }
    
}
