/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.helper.TestConfig;
import io.swagger.client.model.CreateMenuParams;
import io.swagger.client.model.MenuFull;
import io.swagger.client.model.DeleteMenu;
import io.swagger.client.model.ListMenusFull;
import io.swagger.client.model.ReplaceMenuParams;

import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MenusApi
 */
public class MenusApiTest {

    private final MenusApi api = new MenusApi();

    @Before
    public void initTest() {
    	TestConfig.setAuthorization();
    }
    
    /**
     * Create an individual menu
     *
     * This service creates an individual menu. See Account Menus for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountMenuTest() throws ApiException {
        Integer accountId = null;
        CreateMenuParams data = null;
        // MenuFull response = api.createAccountMenu(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Delete an individual menu
     *
     * This service shows the details of an individual menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountMenuTest() throws ApiException {
        Integer accountId = null;
        Integer menuId = null;
        // DeleteMenu response = api.deleteAccountMenu(accountId, menuId);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual menu
     *
     * This service shows the details of an individual Menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountMenuTest() throws ApiException {
        Integer accountId = null;
        Integer menuId = null;
        // MenuFull response = api.getAccountMenu(accountId, menuId);

        // TODO: test validations
    }
    
    /**
     * Get a list of menus for an account
     *
     * See Account Menus for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountMenusTest() throws ApiException {
        Integer accountId = null;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        // ListMenusFull response = api.listAccountMenus(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
    /**
     * Replace an individual menu
     *
     * This service replaces the details of an individual Menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountMenuTest() throws ApiException {
        Integer accountId = null;
        Integer menuId = null;
        ReplaceMenuParams data = null;
        // MenuFull response = api.replaceAccountMenu(accountId, menuId, data);

        // TODO: test validations
    }
    
}
