/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import static org.junit.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.helper.TestConfig;
import io.swagger.client.model.ListPhoneNumbersRegions;

/**
 * API tests for NumberregionsApi
 */
public class NumberRegionsApiTest {

    private final NumberRegionsApi api = new NumberRegionsApi();

    @Before
    public void initTest() {
    	TestConfig.setAuthorization();
    }
    
    /**
     * 
     *
     * This service lists the quantities of available phone numbers by region.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAvailablePhoneNumberRegionsTest() throws ApiException {

    	// Given
        List<String> filtersCountryCode = Arrays.asList("asd");
        List<String> filtersNpa = Arrays.asList("asd");
        List<String> filtersNxx = Arrays.asList("asd");
        List<String> filtersIsTollFree = Arrays.asList("asd");
        List<String> filtersCity = Arrays.asList("asd");
        List<String> filtersProvincePostalCode = Arrays.asList("asd");
        List<String> filtersCountryPostalCode = Arrays.asList("asd");
        String sortCountryCode = "asc";
        String sortNpa = "asc";
        String sortNxx = "asc";
        String sortIsTollFree = "asc";
        String sortCity = "asc";
        String sortProvincePostalCode = "asc";
        String sortCountryPostalCode = "asc";
        Integer limit = 25;
        Integer offset = 0;
        String fields = null;
        List<String> groupBy = null;//Arrays.asList("city");
        
        // When
        ListPhoneNumbersRegions response = api.listAvailablePhoneNumberRegions(filtersCountryCode, filtersNpa, filtersNxx, filtersIsTollFree, filtersCity, filtersProvincePostalCode, filtersCountryPostalCode, sortCountryCode, sortNpa, sortNxx, sortIsTollFree, sortCity, sortProvincePostalCode, sortCountryPostalCode, limit, offset, fields, groupBy);
        
        // Then
        assertNotNull(response.getItems());
    }
    
}
